repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: python -m black .
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff
        name: ruff
        entry: make ruff
        language: system
        types: [python]
        stages: [pre-push]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: make mypy
        language: system
        types: [python]
        stages: [pre-push]
        pass_filenames: false