telegram:
  api_id: 123456
  api_hash: test_api_hash
  bot:
    session_file: test_bot.session
    tokens:
      - test_bot_token
  private_file_channel:
    - '114514'
    - '1919810'
tgfs:
  users:
    test_user:
      password: test_password
      readonly: false
  download:
    chunk_size_kb: 512
  jwt:
    secret: test_jwt_secret
    algorithm: HS256
    life: 3600
  metadata:
    '114514':
      name: test-notes-1
      type: pinned_message
    '1919810':
      name: test-notes-2
      type: github_repo
      github_repo:
          repo: test_user/test_repo
          commit: branch
          access_token: test_github_access_token
  server:
    host: localhost
    port: 8080
