# Any fields in [brackets] are mandatory and should be replaced with your actual values before running the application.

telegram:
  api_id: [your_api_id (mandatory, refer to README)]
  api_hash: [your_api_hash (mandatory, refer to README)]
  account:
    session_file: account.session
    used_to_upload_files: false
  bot:
    session_file: bot.session
    tokens:
        - [your_bot_token (mandatory, apply from @BotFather)]
        # Add more bot tokens if needed, each on a new line
  private_file_channel: [your_channel_id (mandatory, refer to README)]
  public_file_channel: 0

tgfs:
  users:
    user:
      password: password
  download:
    chunk_size_kb: 1024
  jwt:
    secret: [your_jwt_secret (mandatory)]
    algorithm: HS256
    life: 604800
  metadata:
    type: pinned_message

#    type: github_repo
#    github_repo:
#      repo: 'github_username/repo_name'
#      commit: 'master'
#      access_token: github_pat_114514

webdav:
  host: 0.0.0.0
  port: 1900
  path: /
