# Any fields in [brackets] are mandatory and should be replaced with your actual values before running the application.

telegram:
  api_id: [your_api_id (mandatory, refer to README)]
  api_hash: [your_api_hash (mandatory, refer to README)]
  account:
    session_file: account.session
  bot:
    session_file: bot.session
    tokens:
        - [your_bot_token (mandatory, apply from @BotFather)]
        # Add more bot tokens if needed, each on a new line
  private_file_channel: [your_channel_id (mandatory, refer to README)]
  public_file_channel: 0

tgfs:
  users:
    user:
      password: password
  download:
    chunk_size_kb: 1024

webdav:
  host: 0.0.0.0
  port: 1900
  path: /

manager:
  host: 0.0.0.0
  port: 1901
  path: /
  bot:
    token: your_bot_token (optional, apply from @BotFather)
    chat_id: your_chat_id (optional, the chat id between you and your bot. The bot will not reply/send anything to other chats.)
