telegram:
  api_id: your_api_id (mandatory, refer to README)
  api_hash: your_api_hash (mandatory refer to README)
  session_file: ~/.tgfs/your_account.session (optional, default to ~/.tgfs/account.session)
  login_timeout: 300000
  private_file_channel: your_channel_id (mandatory, refer to README)
  public_file_channel: another_channel_id (optional)

tgfs:
  users:
    user:
      password: password
  download:
    progress: true
    chunk_size_kb: 1024

webdav:
  host: 0.0.0.0
  port: 1900
  path: /

manager:
  host: 0.0.0.0
  port: 1901
  path: /
  bot:
    token: your_bot_token (optional, apply from @BotFather)
    chat_id: your_chat_id (optional, the chat id between you and your bot. The bot will not reply/send anything to other chats.)
