export type ErrorCodes =
  | 'UNKNOWN'
  | 'FILE_IS_EMPTY'
  | 'FILE_OR_DIR_ALREADY_EXISTS'
  | 'FILE_OR_DIR_DOES_NOT_EXIST'
  | 'INVALID_NAME'
  | 'RELATIVE_PATH'
  | 'UNKNOWN_COMMAND'
  | 'DIR_IS_NOT_EMPTY'
  | 'FILE_TOO_BIG'
  | 'MESSAGE_NOT_FOUND';
