from enum import Enum


class ErrorCode(Enum):
    UNKNOWN = 0
    FILE_IS_EMPTY = 1
    FILE_OR_DIR_ALREADY_EXISTS = 2
    FILE_OR_DIR_DOES_NOT_EXIST = 3
    INVALID_NAME = 4
    RELATIVE_PATH = 5
    UNKNOWN_COMMAND = 6
    DIR_IS_NOT_EMPTY = 7
    FILE_SIZE_TOO_LARGE = 8
    MESSAGE_NOT_FOUND = 9
    BAD_AUTHENTICATION = 10
    METADATA_NOT_FOUND = 11
    METADATA_NOT_INITIALIZED = 12
    UNDOWNLOADABLE_MESSAGE = 13
    NO_PINNED_MESSAGE = 14
    PINNED_MESSAGE_NOT_SUPPORTED = 15
    TASK_CANCELLED = 16
    LOGIN_FAILED = 17
    DUPLICATED_CHANNEL_ID_OR_NAME = 18
