name: docker-build-push

on:
  workflow_run:
    workflows: ["Test and Coverage"]
    types:
      - completed
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        include:
          - name: tgfs
            dockerfile: Dockerfile
            repository: wheatcarrier/tgfs
          - name: tgfs-fe
            dockerfile: Dockerfile.frontend
            repository: wheatcarrier/tgfs-fe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ matrix.repository }}:latest
            ${{ matrix.repository }}:${{ github.sha }}
